import "../globals.css";
import localFont from "next/font/local";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Header from "@/components/home/header";

const interTight = localFont({
  src: [
    {
      path: "../../fonts/InterTight-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../fonts/InterTight-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/InterTight-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/InterTight-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../fonts/InterTight-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../fonts/InterTight-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../fonts/InterTight-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-inter",
});

export const metadata = {
  title: "Solvex Network",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ params, children }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={`${interTight.variable} font-inter antialiased gridContainer fluid bg-dark-black`}>
        <NextIntlClientProvider>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
